= TBT Cloud

image::https://tbt-post.net/images/TBT-Cloud-icon.svg[TBT Cloud,200,role="right"]

**TBT Cloud** is the turnkey cloud solution to boost and empower retail, warehousing and e-commerce businesses. 

Initially built as an enterprise solution for kasta.ua (ex modnakasta) during its digital transformation.
To day the platform empowers different on-line projects by providing all-in-one toolchain and standalone features to drive retail and warehousing in Eastern Europe.

For a public market **TBT Cloud** supplies SaaS-es to carry on warehousing and logistic (**WMS**), 
manage branches and deliveries (**BMS**) and also wide range of other tools together with builtins 
for **financial integrations** accomplished by own **deep expertise**.

From 2022 **TBT Cloud** is a part of https://github.com/dkdhub[**DKDHUB**]. All repositories under this project are frozen and are the subject of migration to the https://github.com/dkdhub[Main DKDHUB repository]

Please see more on https://www.linkedin.com/products/updcon-dkdhub/[product page on LinkedIn]

All the dedicated instances of TBT Cloud reamain operational till the end of 2023.
